file:
  find_best_model: True
  model_name_use: ""
model:
  n_encoder_layers: 2
  dim_values: [32]
  n_heads: 4
  dropout: 0.1
  train_new_model: False
  seed_experiment: False
  

training:
  learning_rates: [0.0005]  
  n_epochs: [1000]
  batch_sizes: [32]
  electron_range: 24
  num_workers: 4

data:
  forecasts_out: [6,12]    # 6 = 30min, 12 = 60min
  train_split: 0.8